#!/bin/sh -e

# install alternatives links

if [ "$1" = "configure" ]; then
  update-alternatives --install /usr/bin/x-terminal-emulator \
  x-terminal-emulator /usr/bin/Terminal.wrapper 40 \
  --slave /usr/share/man/man1/x-terminal-emulator.1.gz \
  x-terminal-emulator.1.gz /usr/share/man/man1/Terminal.1.gz
fi

#DEBHELPER#

exit 0
