.\" Copyright (C) 2004 Benedikt Meurer
.TH TERMINAL "1" "February 2004" "Terminal 0.1.2" "User Commands"
.SH NAME
Terminal \- X Terminal emulator
.SH SYNOPSIS
.B Terminal
.SH DESCRIPTION
.PP
Starts the Terminal application.
.SH "REPORTING BUGS"
Report bugs to <benny@xfce.org>.
.SH COPYRIGHT
Copyright \(co 2004 Benedikt Meurer
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
